### ISSUE TITLE
Encountering a `Bad Gateway` error on Grafana when using tempo as a source

### ISSUE THREAD

**Issue by shayancanonical** [canonical/tempo-k8s-operator#114]
### Bug Description

I am encountering a `Bad Gateway` error when using tempo-k8s (from the edge channel, revision 48) as a source in Grafana. Using stable (revision 30) results in a working dashboard.

![image](https://github.com/canonical/tempo-k8s-operator/assets/99665202/e5ee3047-7d40-4773-a35b-b7771ab4b5fb)

### To Reproduce

1. switch to a k8s controller
2. juju add-model cos
3. juju deploy cos-lite --trust
4. juju deploy tempo-k8s --channel edge
5. jhack imatrix fill
6. after everything is active/idle, `juju run grafana/leader get-admin-password --model cos`
7. go to grafana, and try to explore with tempo as a source

### Environment

juju: 3.4.2
microk8s:  v1.27.13 revision 6744
tempo-k8s: revision 48

### Relevant log output

```shell
unit-tempo-k8s-0: 20:01:18 ERROR unit.tempo-k8s/0.juju-log tracing:34: Exception while exporting Span batch.                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                 
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/urllib3/connectionpool.py", line 793, in urlopen                                                                                                          
    response = self._make_request(                                                                                                                                                                                 
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/urllib3/connectionpool.py", line 537, in _make_request                                                                                                    
    response = conn.getresponse()                                                                                                                                                                                  
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/urllib3/connection.py", line 466, in getresponse                                                                                                          
    httplib_response = super().getresponse()                                                                                                                                                                       
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse                                                                                                                                             
    response.begin()                                                                                                                                                                                               
  File "/usr/lib/python3.10/http/client.py", line 318, in begin                                                                                                                                                    
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/urllib3/connectionpool.py", line 847, in urlopen 
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/urllib3/connectionpool.py", line 793, in urlopen 
    response = self._make_request(
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/urllib3/connection.py", line 466, in getresponse 
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/opentelemetry/sdk/trace/export/__init__.py", line 368, in _export_batch
    self.span_exporter.export(self.spans_list[:idx])  # type: ignore
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 145, in export
    resp = self._export(serialized_data)
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 114, in _export
    return self._session.post(
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
```


### Additional context

_No response_

**Comment by mmkay** [comment]
Hi @shayancanonical! Do you see it with `stable` COS-lite bundle?

**Comment by mmkay** [comment]
Tried to reproduce it on both `stable` and `edge` COS-lite. It works for me on `edge` and `beta` and started appearing with the change from #94 where we added a proper support of traefik-route (so cross-model relations). We already fixed the issue in canonical/traefik-k8s-operator#353 - you should be able to use `stable` traefik once rev189 lands on stable (so in a few weeks). Closing the issue for now, feel free to reopen if it reproduces also on `edge` on your environment.
