### ISSUE TITLE
charm_tracing: Tracing types having decorated methods can fail

### ISSUE THREAD

**Issue by gboutry** [canonical/tempo-k8s-operator#155]
### Bug Description

I tried to trace the type `charms.data_platform_libs.v0.data_interfaces.DatabaseRequires`, but it fails because the method reported name is `wrapper` instead of the method name on the type.

### To Reproduce

```python
import functools
import inspect

def working_wrapper(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        print("Before")
        result = func(*args, **kwargs)
        print("After")
        return result
    return wrapper

def broken_wrapper(func):
    def wrapper(*args, **kwargs):
        print("Before")
        result = func(*args, **kwargs)
        print("After")
        return result
    return wrapper


class MyC:
    @working_wrapper
    def working(self):
        print("Working")

    @broken_wrapper
    def broken(self):
        print("Broken")

cls = MyC

def trace_method(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        print(f"Tracing {func.__name__}")
        return func(*args, **kwargs)
    return wrapper

for name, method in inspect.getmembers(cls, predicate=inspect.isfunction):
    print(f"discovered {method}: {name}, {method.__name__}")

    if method.__name__.startswith("__"):
        print(f"skipping {method} (dunder)")
        continue

    try:
        attribute = inspect.getattr_static(cls, method.__name__)
    except AttributeError:
        print(f"cannot assert staticness of {method}, is it a wrapper not updated?")
        continue

    new_method = trace_method(method)
    if isinstance(attribute, staticmethod):
        new_method = staticmethod(new_method)
    setattr(cls, name, new_method)
    print(f"updated {method} to {new_method}")

my_c = MyC()
my_c.working()
my_c.broken()
```

### Environment

charm_tracing v1.11

### Relevant log output

```shell
2024-07-31T07:34:05.496Z [container-agent] 2024-07-31 07:34:05 ERROR juju-log Uncaught exception while in charm code:                                                                                                                                    
2024-07-31T07:34:05.496Z [container-agent] Traceback (most recent call last):                                                                                                                                                                            
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/./src/charm.py", line 1826, in <module>                                                                                                                    
2024-07-31T07:34:05.496Z [container-agent]     main(KeystoneOperatorCharm)                                                                                                                                                                               
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/main.py", line 549, in main                                                                                                                       
2024-07-31T07:34:05.496Z [container-agent]     manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)                                                                                                                                
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/main.py", line 432, in __init__                                                                                                                   
2024-07-31T07:34:05.496Z [container-agent]     self.charm = self._make_charm(self.framework, self.dispatcher)                                                                                                                                            
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/venv/ops/main.py", line 435, in _make_charm                                                                                                                
2024-07-31T07:34:05.496Z [container-agent]     charm = self._charm_class(framework)                                                                                                                                                                      
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 376, in wrap_init                                                                                          
2024-07-31T07:34:05.496Z [container-agent]     original_init(self, framework, *args, **kwargs)                                                                                                                                                           
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/./src/charm.py", line 363, in __init__                                                                                                                     
2024-07-31T07:34:05.496Z [container-agent]     super().__init__(framework)                                                                                                                                                                               
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/ops_sunbeam/charm.py", line 777, in __init__                                                                                                           
2024-07-31T07:34:05.496Z [container-agent]     super().__init__(framework)                                                                                                                                                                               
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/ops_sunbeam/charm.py", line 579, in __init__                                                                                                           
2024-07-31T07:34:05.496Z [container-agent]     super().__init__(framework)                                                                                                                                                                               
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/ops_sunbeam/charm.py", line 100, in __init__                                                                                                           
2024-07-31T07:34:05.496Z [container-agent]     self.relation_handlers = self.get_relation_handlers()                                                                                                                                                     
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 653, in wrapped_function                                                                                   
2024-07-31T07:34:05.496Z [container-agent]     return callable(*args, **kwargs)  # type: ignore                                                                                                                                                          
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/./src/charm.py", line 932, in get_relation_handlers                                                                                                        
2024-07-31T07:34:05.496Z [container-agent]     return super().get_relation_handlers(handlers)                                                                                                                                                            
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/ops_sunbeam/charm.py", line 821, in get_relation_handlers                                                                                              
2024-07-31T07:34:05.496Z [container-agent]     return super().get_relation_handlers(handlers)                                                                                                                                                            
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/ops_sunbeam/charm.py", line 679, in get_relation_handlers                                                                                              
2024-07-31T07:34:05.496Z [container-agent]     return super().get_relation_handlers(handlers)                                                                                                                                                            
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/ops_sunbeam/charm.py", line 159, in get_relation_handlers                                                                                              
2024-07-31T07:34:05.496Z [container-agent]     db = sunbeam_rhandlers.DBHandler(                                                                                                                                                                         
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/ops_sunbeam/relation_handlers.py", line 279, in __init__                                                                                               
2024-07-31T07:34:05.496Z [container-agent]     super().__init__(charm, relation_name, callback_f, mandatory)                                                                                                                                             
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/ops_sunbeam/relation_handlers.py", line 90, in __init__                                                                                                
2024-07-31T07:34:05.496Z [container-agent]     self.interface = self.setup_event_handler()                                                                                                                                                               
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 653, in wrapped_function                                                                                   
2024-07-31T07:34:05.496Z [container-agent]     return callable(*args, **kwargs)  # type: ignore                                                                                                                                                          
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/ops_sunbeam/relation_handlers.py", line 296, in setup_event_handler                                                                                    
2024-07-31T07:34:05.496Z [container-agent]     db = sunbeam_tracing.trace_type(DatabaseRequires)(                                                                                                                                                        
2024-07-31T07:34:05.496Z [container-agent]   File "/var/lib/juju/agents/unit-keystone-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 616, in trace_type                                                                                         
2024-07-31T07:34:05.496Z [container-agent]     attribute = inspect.getattr_static(cls, method.__name__)                                                                                                                                                  
2024-07-31T07:34:05.496Z [container-agent]   File "/usr/lib/python3.10/inspect.py", line 1769, in getattr_static                                                                                                                                         
2024-07-31T07:34:05.496Z [container-agent]     raise AttributeError(attr)                                                                                                                                                                                
2024-07-31T07:34:05.496Z [container-agent] AttributeError: wrapper
```

### Additional context

Reproducer script output:
```
discovered <function broken_wrapper.<locals>.wrapper at 0x7d9542af31c0>: broken, wrapper
cannot assert staticness of <function broken_wrapper.<locals>.wrapper at 0x7d9542af31c0>, is it a wrapper not updated?
discovered <function MyC.working at 0x7d9542af30a0>: working, working
updated <function MyC.working at 0x7d9542af30a0> to <function MyC.working at 0x7d9542af3250>
Tracing working
Before
Working
After
Before
Broken
After
```

**Comment by gboutry** [comment]
There's multiple ways to solve this issue, either just skip a method like that, or use `name` instead `method.__name__`. This works, but then the name reported in the tracing will not be great.

In any case, this library should not error out on this case.

**Comment by PietroPasotti** [comment]
definitely shouldn't error out. 
Funnily enough I think we don't need to do `method.__name__` at all because we already have the qualname of the method (from inspect.getmembers).

The fix should be straightforward

**Comment by PietroPasotti** [comment]
Wondering if we should display nicely the presence of the decorator in the span.
Context:
![image](https://github.com/user-attachments/assets/76e87fba-d8c3-4e8c-892f-affe71a27f90)

option A:
```
method call: MyCharmWrappedMethods.a
method call: @bad_wrapper(MyCharmWrappedMethods.b)
```


option B (plain, no indication that there's a user decorator at play):
```
method call: MyCharmWrappedMethods.a
method call: MyCharmWrappedMethods.b
```

@gboutry @mmkay WDYT?

**Comment by gboutry** [comment]
I wonder what the spans look like if we do:

```python
import functools

def wrapity(f):
  @functools.wraps(f)
  @trace_function
  def wrapper(*args, **kwargs):
    return func(*args, **kwargs)
  return wrapper

my_func = wrapity(my_func)

# spans for this??
my_func()
```

**Comment by PietroPasotti** [comment]
they'll look like `method call: MyCharmWrappedMethods.wrapity`, because `trace_function` runs first and at that point in time there's no `__name__` set yet
