### ISSUE TITLE
Deploying tempo-k8s charm fails

### ISSUE THREAD

**Issue by bencekov** [canonical/tempo-k8s-operator#37]
### Bug Description

Deploying tempo-k8s fails due to an error in the charm code. I packed the charm from the current main branch.

### To Reproduce

git clone https://github.com/canonical/tempo-k8s-operator
cd tempo-k8s-operator
charmcraft pack
juju deploy ./tempo*charm  --resource tempo-image=$(yq eval '.resources.tempo-image.upstream-source' metadata.yaml)  --trust

### Environment

charmcraft version 2.4.0 latest/beta
juju version 3.1.5

### Relevant log output

```shell
unit-tempo-k8s-0: 15:09:17 WARNING unit.tempo-k8s/0.install Traceback (most recent call last):
unit-tempo-k8s-0: 15:09:17 WARNING unit.tempo-k8s/0.install   File "./src/charm.py", line 16, in <module>
unit-tempo-k8s-0: 15:09:17 WARNING unit.tempo-k8s/0.install     from charms.tempo_k8s.v0.charm_instrumentation import trace_charm
unit-tempo-k8s-0: 15:09:17 WARNING unit.tempo-k8s/0.install   File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/lib/charms/tempo_k8s/v0/charm_instrumentation.py", line 65, in <module>
unit-tempo-k8s-0: 15:09:17 WARNING unit.tempo-k8s/0.install     from grpc import ChannelCredentials
unit-tempo-k8s-0: 15:09:17 WARNING unit.tempo-k8s/0.install   File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/grpc/__init__.py", line 22, in <module>
unit-tempo-k8s-0: 15:09:17 WARNING unit.tempo-k8s/0.install     from grpc import _compression
unit-tempo-k8s-0: 15:09:17 WARNING unit.tempo-k8s/0.install   File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/grpc/_compression.py", line 20, in <module>
unit-tempo-k8s-0: 15:09:17 WARNING unit.tempo-k8s/0.install     from grpc._cython import cygrpc
unit-tempo-k8s-0: 15:09:17 WARNING unit.tempo-k8s/0.install ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/grpc/_cython/__init__.py)
```

**Comment by sed-i** [comment]
The issue is that we are running on 20.04 (py38), but the cygrpc name is for a py310:

```
root@tempo-0:/var/lib/juju# find / -type f -name "cygrpc*"
/var/lib/juju/agents/unit-tempo-0/charm/venv/grpc/_cython/cygrpc.cpython-310-x86_64-linux-gnu.so

root@tempo-0:/var/lib/juju# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```
